version: '3.8'

services:
  kong-database:
    image: postgres:10  # ← バージョン10に変更
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
      - ./init-konga-db.sql:/docker-entrypoint-initdb.d/init-konga-db.sql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  kong:
    image: kong:3.6.0
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PLUGINS: bundled
      # ← 追加：httpコンテキストにインクルード
      KONG_NGINX_HTTP_INCLUDE: /usr/local/kong/nginx-http.conf
    ports:
      - "8000:8000"  # Proxy
      - "8001:8001"  # Admin API
    command: ["kong", "docker-start"]
    volumes:
      - ./kong-nginx-http.conf:/usr/local/kong/nginx-http.conf:ro

  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    environment:
      - NODE_ENV=development
      #- NODE_ENV=production
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_USER=kong
      - DB_PASSWORD=kong
      - DB_DATABASE=konga
    ports:
      - "1337:1337"
    depends_on:
      - kong-database
    
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  quarkus-authz:
    build:
      context: ./quarkus-authz
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    ports:
      - "8081:8080"

volumes:
  kong_data:
